export { default as Header } from "./Header/Header.jsx";
export { default as Social } from "./Social/Social.jsx";
export { default as Info } from "./Info/Info.jsx";
export { default as ScrollDown } from "./ScrollDown/ScrollDown.jsx";
export { default as AboutInfo } from "./AboutInfo/AboutInfo.jsx";
export { default as FrontEnd } from "./FrontEnd/FrontEnd.jsx";
export { default as BackEnd } from "./BackEnd/BackEnd.jsx";
export { default as Services } from "./Services/Services.jsx";
export { default as Qualification } from "./Qualification/Qualification.jsx";
